// Exact semantic aliases only. Unknown provider metrics remain missing, never zero.
export const STATEMENT_FIELDS: Record<string, Record<string, string[]>> = {
  IS: {
    revenue: ['revenue', 'total-revenue'],
    costOfRevenue: ['cost-of-revenue'],
    grossProfit: ['gross-profit'],
    operatingIncome: ['operating-income'],
    operatingExpenses: ['operating-expenses'],
    researchAndDevelopmentExpenses: ['research-and-development'],
    sellingGeneralAndAdministrativeExpenses: ['selling-general-and-administrative'],
    netIncome: ['net-income', 'income-towards-parent-company', 'net-income-towards-common-stockholders', 'consolidated-net-income'],
    eps: ['eps-basic'],
    epsDiluted: ['eps-weighted-average-and-diluted', 'eps-diluted'],
    weightedAverageShsOut: ['shares-outstanding-weighted-average'],
    weightedAverageShsOutDil: ['shares-outstanding-diluted-average'],
    ebitda: ['ebitda'],
    ebit: ['ebit'],
    incomeBeforeTax: ['ebt', 'income-before-tax'],
    incomeTaxExpense: ['tax-provisions', 'income-tax-expense'],
    interestExpense: ['interest-expenses', 'interest-expense'],
    depreciationAndAmortization: ['depreciation-and-amortization-total', 'depreciation-amortization-total'],
  },
  BS: {
    totalAssets: ['total-assets', 'assets'],
    totalCurrentAssets: ['total-current-assets', 'current-assets'],
    totalCurrentLiabilities: ['total-current-liabilities', 'current-liabilities'],
    totalLiabilities: ['total-liabilities', 'liabilities'],
    totalStockholdersEquity: ['total-stockholders-equity', 'stockholders-equity', 'shareholders-equity', 'total-shareholders-equity', 'equity-towards-parent-company'],
    cashAndCashEquivalents: ['cash-and-equivalents', 'cash-and-cash-equivalents', 'cash-cash-equivalents'],
    cashAndShortTermInvestments: ['cash-and-short-term-investments', 'cash-cash-equivalents-and-short-term-investments'],
    shortTermInvestments: ['short-term-investments', 'short-term-marketable-securities'],
    totalDebt: ['total-debt'],
    shortTermDebt: ['short-term-debt'],
    longTermDebt: ['long-term-debt'],
    netDebt: ['net-debt'],
    inventory: ['inventory', 'inventories'],
    netReceivables: ['accounts-receivables', 'accounts-receivable', 'receivables-net'],
    goodwill: ['goodwill'],
    intangibleAssets: ['intangible-assets', 'intangible-assets-net'],
    propertyPlantEquipmentNet: ['property-plant-and-equipment-net', 'property-plant-equipment-net'],
    retainedEarnings: ['retained-earnings'],
  },
  CF: {
    operatingCashFlow: ['cash-from-operating-activities', 'net-cash-from-operating-activities', 'operating-cash-flow', 'cash-from-operations'],
    capitalExpenditure: ['capital-expenditure', 'capital-expenditures', 'capex'],
    freeCashFlow: ['free-cash-flow'],
    stockBasedCompensation: ['stock-based-compensation', 'share-based-compensation'],
    netCommonStockIssuance: ['net-common-stock-issuance'],
    commonStockIssuance: ['common-stock-issuance', 'issuance-of-common-stock'],
    commonStockRepurchased: ['common-stock-repurchased', 'repurchase-of-common-stock'],
    dividendsPaid: ['dividends-paid', 'cash-dividends-paid'],
    netCashUsedForInvestingActivites: ['cash-from-investing-activities', 'net-cash-from-investing-activities'],
    netCashUsedProvidedByFinancingActivities: ['cash-from-financing-activities', 'net-cash-from-financing-activities'],
    depreciationAndAmortization: ['depreciation-and-amortization', 'depreciation-and-amortization-total'],
  },
  Ratios: {
    currentRatio: ['current-ratio'],
    debtToEquityRatio: ['debt-to-equity', 'debt-to-equity-ratio'],
    priceToEarningsRatio: ['price-to-earnings', 'price-to-earnings-ratio', 'p-e-ratio'],
    priceToSalesRatio: ['price-to-sales', 'price-to-sales-ratio'],
    netProfitMargin: ['net-margin', 'net-profit-margin'],
  },
};
